<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRwbwg4c\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRwbwg4c/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerRwbwg4c.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerRwbwg4c\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerRwbwg4c\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Rwbwg4c',
    'container.build_id' => '0dc758d1',
    'container.build_time' => 1525163209,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerRwbwg4c');
