<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVhxz3bw\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVhxz3bw/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerVhxz3bw.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerVhxz3bw\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerVhxz3bw\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Vhxz3bw',
    'container.build_id' => '384023c5',
    'container.build_time' => 1526923510,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerVhxz3bw');
