<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerO6bidzj\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerO6bidzj/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerO6bidzj.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerO6bidzj\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerO6bidzj\appDevDebugProjectContainer(array(
    'container.build_hash' => 'O6bidzj',
    'container.build_id' => 'f8f7d5f3',
    'container.build_time' => 1526050707,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerO6bidzj');
